feat: if yarn not found install it

diff --git a/.github/actions/setup/action.yml b/.github/actions/setup/action.yml
--- a/.github/actions/setup/action.yml
+++ b/.github/actions/setup/action.yml
@@ -88,6 +88,22 @@ runs:
         echo "SCCACHE_S3_KEY_PREFIX=bendsql/sccache/" >> $GITHUB_ENV
         echo "SCCACHE_S3_USE_SSL=true" >> $GITHUB_ENV
 
+    - name: Install Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '18'
+
+    - name: Install Yarn
+      shell: bash
+      run: |
+        if ! command -v yarn &> /dev/null
+        then
+          echo "Yarn not found, installing..."
+          npm install --global yarn
+        else
+          echo "Yarn is already installed"
+        fi
+
     - name: Install Frontend
       working-directory: frontend
       shell: bash
